import localesIndexJSWriter from '../lib/fileWriter/localesIndexJSWriter';
import vueWriter from '../lib/fileWriter/vueWriter';
import jsConfigJsonWriter from '../lib/fileWriter/jsConfigJsonWriter';
import commonWriter from '../lib/fileWriter/commonWriter';
import tsCommonWriter from '../lib/fileWriter/tsCommonWriter';
import mockJSWriter from '../lib/fileWriter/mockJSWriter';
import andDesignVueWriter from '../lib/fileWriter/antDesignVueWriter';
import Util from './util';

export default {
  dirs:["__test__",
      "dist",
      "src",
      "src/api",
      "src/assets",
      "src/assets/images",
      "src/assets/fonts",
      "src/assets/css",
      "src/assets/js",
      "src/components",
      "src/config",
      "src/locales",
      "src/model",
      "src/pages",
      "src/pages/home",
      "src/pages/notFound",
      "src/plugins",
      "src/state",
      "src/mock",
      "src/themes",
      "src/utils",
  ],
  files:[
  {
    type:'less',
    fileName:"src/themes/index.less",
    writer:commonWriter,
    template:'themes/index.less.art',
    override:false
  },
  {
    type:'js',
    fileName:"src/themes/modifyVars.js",
    writer:commonWriter,
    template:'themes/modifyVars.js.art',
    override:false
  },
  // ant-design-vue 文件
  {
    type:'less',
    fileName:"src/themes/antd.less",
    writer:andDesignVueWriter,
    template:'themes/ant-design-vue/antd.less.art',
    override:false
  },
  {
    type:'less',
    fileName:"src/themes/bezierEasing.less",
    writer:andDesignVueWriter,
    template:'themes/ant-design-vue/bezierEasing.less.art',
    override:false
  },
  {
    type:'less',
    fileName:"src/themes/colorPalette.less",
    writer:andDesignVueWriter,
    template:'themes/ant-design-vue/colorPalette.less.art',
    override:false
  },
  {
    type:'less',
    fileName:"src/themes/colors.less",
    writer:andDesignVueWriter,
    template:'themes/ant-design-vue/colors.less.art',
    override:false
  },
  {
    type:'less',
    fileName:"src/themes/tinyColor.less",
    writer:andDesignVueWriter,
    template:'themes/ant-design-vue/tinyColor.less.art',
    override:false
  },
  {
    type:'js',
    fileName:"src/locales/index.js",
    writer:localesIndexJSWriter,
    override:false,
  },
  {
    type:'js|ts',
    fileName:"src/config/routes.*",
    writer:commonWriter,
    template:'config/routes.js.art',
    override:true,
  },
  {
    type:'js|ts',
    fileName:"src/config/components.*",
    writer:commonWriter,
    template:'config/components.js.art',
    override:true,
  },
  {
    type:'js|ts',
    fileName:"src/app.config.*",
    writer:commonWriter,
    template:'app.config.js.art',
    override:false
  },
  {
    type:'js',
    fileName:"cli.config.js",
    writer:commonWriter,
    template:'cli.config.js.art',
    override:false
  },
  {
    type:'js|ts',
    fileName:"src/app.*",
    writer:commonWriter,
    template:'app.js.art',
    override:false
  },
  {
    type:'ts',
    fileName:"src/global.d.ts",
    writer:tsCommonWriter,
    template:'global.d.ts.art',
    override:false
  },
  {
    type:'vue',
    fileName:"src/app.vue",
    writer:commonWriter,
    template:'app.vue.art',
    override:false
  },
  {
    type:'json',
    fileName:"package.json",
    writer:commonWriter,
    template:'package.json.art',
    override:false
  },
  {
    type:'git',
    fileName:".gitignore",
    writer:commonWriter,
    template:'gitignore.art',
    override:false
  },
  {
    type:'eslint',
    fileName:".eslintrc.js",
    writer:commonWriter,
    template:'eslintrc.js.art',
    override:true
  },
  {
    type:'js|ts',
    fileName:"src/plugins/app.*",
    writer:commonWriter,
    template:'plugins.app.js.art',
    override:false
  },
  {
    type:'vue',
    fileName:"src/pages/home/index.vue",
    writer:vueWriter,
    template:'pages/home/index.vue.art',
    override:false
  },
  {
    type:'less',
    fileName:"src/pages/home/index.less",
    writer:commonWriter,
    template:'pages/home/index.less.art',
    override:false
  },
  {
    type:'js|ts',
    fileName:"src/pages/home/index.*",
    writer:commonWriter,
    template:'pages/home/index.js.art',
    override:false
  },
  {
    type:'vue',
    fileName:"src/pages/notFound/index.vue",
    writer:vueWriter,
    template:'pages/notFound/index.vue.art',
    override:false
  },
  {
    type:'json',
    fileName:"tsconfig.json",
    writer:tsCommonWriter,
    template:'tsconfig.json.art',
    override:true
  },
  {
    type:'json',
    fileName:"jsconfig.json",
    writer:jsConfigJsonWriter,
    template:'jsconfig.json.art',
    override:true
  },
  {
    type:'js',
    fileName:"jest.config.js",
    writer:commonWriter,
    template:'jest.config.js.art',
    override:true
  },
  {
    type:'js',
    fileName:"babel.config.js",
    writer:commonWriter,
    template:'babel.config.js.art',
    override:true
  },
  {
    type:'js|ts',
    fileName:"src/mock/index.*",
    writer:mockJSWriter,
    template:Util.getMockTemplateFile(),
    override:false
  },
  {
    type:'js|ts',
    fileName:"src/utils/number.*",
    writer:commonWriter,
    template:'utils/number.js.art',
    override:false
  },
  {
    type:'js|ts',
    fileName:"__test__/number.spec.*",
    writer:commonWriter,
    template:'__test__/number.spec.js.art',
    override:false
  },
  {
    type:'js|ts',
    fileName:"__test__/counter.spec.*",
    writer:commonWriter,
    template:'__test__/counter.spec.js.art',
    override:false
  },
]
}